name: Deploy to Gov PaaS

on:
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        required: false
        default: false
        type: boolean
        description: Deploy to dev?
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  test_and_deploy:
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/deploy.yml@fs-2415-standardise-github-workflows
    with:
      app_name: ${{ github.event.repository.name }}
      api: true
      postgres_unit_testing: true
      db_name: fsd_assess_store_test
      deploy_to_dev: ${{github.event.inputs.deploy_to_dev == 'true'}}
      run_performance_tests: true
      run_e2e_tests: true
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USERNAME}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
      E2E_PAT: ${{secrets.E2E_PAT}}
      RSA256_PUBLIC_KEY_BASE64: ${{secrets.RSA256_PUBLIC_KEY_BASE64}}
